services:
  db:
    image: postgres:15
    container_name: webapp_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

  web:
    build: .
    container_name: webapp_web
    restart: always
    ports:
      - "8050:8050"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./data:/app/data

  pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile.pipeline
    container_name: webapp_pipeline
    restart: no
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./data:/app/data
      - ./pipeline:/app/pipeline
    dns:
      - 1.1.1.1
      - 8.8.8.8
    mem_limit: 1800m
    memswap_limit: 1800m
    cpus: 1.0

  db_init:
    build:
      context: ./pipeline
      dockerfile: Dockerfile.pipeline
    working_dir: /app
    container_name: webapp_db_init
    restart: "no"
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./pipeline:/app/pipeline
    command: ["sh", "/app/pipeline/init_db.sh"]
    
volumes:
  db_data:
