FROM python:3.12-slim

WORKDIR /app

# Install tzdata
RUN apt-get update && apt-get install -y tzdata
ENV TZ=Europe/Zurich
RUN ln -snf /usr/share/zoneinfo/Europe/Zurich /etc/localtime && echo "Europe/Zurich" > /etc/timezone

# Copy only pipeline scripts (not data)
COPY ./requirements.txt ./requirements.txt
COPY ./run_pipeline.sh ./run_pipeline.sh

# Install Python requirements
RUN pip install --no-cache-dir -r requirements.txt

CMD ["sh", "/app/run_pipeline.sh"]
